use FiapSmartCityMVC;

CREATE TABLE PRODUCTEF (
  PRODUCTID				     INT identity(1,1)    PRIMARY KEY,
  PRODUCTNAME			     VARCHAR(70)          NOT NULL,
  FEATURES				     VARCHAR(100)         NOT NULL,
  AVERAGEPRICE			   money,
  LOGOTIPO      		   VARCHAR(200)         NOT NULL,
  ACTIVE  				     INT,
  TYPEID				       INT,
  CONSTRAINT FK_TYPEID FOREIGN KEY (TYPEID) REFERENCES PRODUCTTYPEEF(TYPEID)
);